\ ******************************************************************************
\ * Object sprite data (two-stream format)                                     *
\ *                                                                            *
\ * AUTO-GENERATED by tools/sprite_editor.py -- do not hand-edit.              *
\ * Original data lives in thrust.6502 inside IF _SWRAM_BUILD=FALSE. This file *
\ * is INCLUDEd in the SWRAM build so edits here take effect without touching  *
\ * the main source.                                                           *
\ ******************************************************************************

.obj_sprite_data_A_gun_up_right
        EQUB    $88,$10,$18,$80,$08,$10,$18,$80
        EQUB    $10,$18,$80,$10,$18,$20,$80,$08
        EQUB    $18,$20,$90,$18,$20,$90,$18,$20
        EQUB    $98,$20,$98,$20,$A0,$A0,$A0,$A0
        EQUB    $A0,$FF
.obj_sprite_data_B_gun_up_right
        EQUB    $66,$77,$88,$11,$99,$88,$66,$66
        EQUB    $66,$11,$88,$11,$88,$88,$FF,$FF
        EQUB    $66,$88,$EE,$11,$88,$11,$88,$66
        EQUB    $66,$11,$11,$11,$99,$99,$55,$55
        EQUB    $33,$FF

.obj_sprite_data_A_gun_down_right
        EQUB    $20,$A0,$A0,$A0,$A0,$98,$20,$98
        EQUB    $20,$90,$18,$20,$90,$18,$20,$80
        EQUB    $08,$18,$20,$80,$10,$18,$20,$80
        EQUB    $10,$18,$80,$08,$10,$18,$88,$10
        EQUB    $18,$FF
.obj_sprite_data_B_gun_down_right
        EQUB    $33,$55,$55,$99,$99,$11,$11,$66
        EQUB    $11,$11,$88,$66,$EE,$11,$88,$FF
        EQUB    $FF,$66,$88,$88,$11,$88,$88,$66
        EQUB    $66,$11,$11,$99,$88,$66,$66,$77
        EQUB    $88,$FF

.obj_sprite_data_A_gun_up_left
        EQUB    $88,$10,$18,$88,$10,$18,$20,$88
        EQUB    $10,$20,$80,$08,$10,$20,$80,$08
        EQUB    $18,$20,$80,$08,$10,$80,$08,$10
        EQUB    $80,$08,$80,$08,$80,$80,$80,$80
        EQUB    $80,$FF
.obj_sprite_data_B_gun_up_left
        EQUB    $11,$EE,$66,$66,$11,$99,$88,$88
        EQUB    $66,$66,$11,$11,$88,$11,$11,$66
        EQUB    $FF,$FF,$11,$88,$77,$66,$11,$88
        EQUB    $88,$66,$88,$88,$99,$99,$AA,$AA
        EQUB    $CC,$FF

.obj_sprite_data_A_gun_down_left
        EQUB    $00,$80,$80,$80,$80,$80,$08,$80
        EQUB    $08,$80,$08,$10,$80,$08,$10,$80
        EQUB    $08,$18,$20,$80,$08,$10,$20,$88
        EQUB    $10,$20,$88,$10,$18,$20,$88,$10
        EQUB    $18,$FF
.obj_sprite_data_B_gun_down_left
        EQUB    $CC,$AA,$AA,$99,$99,$88,$88,$88
        EQUB    $66,$66,$11,$88,$11,$88,$77,$11
        EQUB    $66,$FF,$FF,$11,$11,$88,$11,$88
        EQUB    $66,$66,$66,$11,$99,$88,$11,$EE
        EQUB    $66,$FF

.obj_sprite_data_A_fuel
        EQUB    $00,$08,$10,$18,$80,$18,$80,$18
        EQUB    $80,$08,$10,$18,$80,$08,$10,$18
        EQUB    $80,$08,$10,$18,$80,$08,$10,$18
        EQUB    $80,$08,$10,$18,$80,$18,$80,$18
        EQUB    $80,$08,$10,$18,$88,$10,$80,$08
        EQUB    $10,$18,$80,$18,$FF
.obj_sprite_data_B_fuel
        EQUB    $01,$0F,$0F,$08,$06,$06,$08,$01
        EQUB    $0B,$70,$66,$49,$0B,$70,$66,$85
        EQUB    $0B,$70,$66,$49,$0B,$70,$66,$85
        EQUB    $0B,$70,$66,$49,$08,$01,$06,$06
        EQUB    $01,$0F,$0F,$08,$88,$11,$11,$88
        EQUB    $11,$88,$11,$88,$FF

.obj_sprite_data_A_pod_stand
        EQUB    $90,$88,$10,$18,$88,$10,$18,$88
        EQUB    $10,$18,$88,$10,$18,$88,$10,$18
        EQUB    $88,$10,$18,$88,$10,$18,$88,$10
        EQUB    $18,$88,$10,$18,$90,$88,$18,$88
        EQUB    $10,$18,$88,$18,$88,$10,$18,$90
        EQUB    $90,$90,$88,$10,$FF
.obj_sprite_data_B_pod_stand
        EQUB    $EE,$33,$B1,$88,$54,$50,$44,$64
        EQUB    $A0,$C4,$D8,$50,$62,$A8,$A0,$E2
        EQUB    $D8,$50,$E2,$64,$B0,$C4,$54,$70
        EQUB    $C4,$33,$F1,$88,$EE,$02,$08,$05
        EQUB    $0F,$04,$04,$04,$03,$01,$08,$0A
        EQUB    $0A,$0A,$01,$01

.obj_sprite_data_A_generator
        EQUB    $08,$10,$18,$88,$18,$20,$80,$08
        EQUB    $18,$20,$80,$20,$80,$20,$80,$20
        EQUB    $80,$20,$80,$20,$80,$20,$80,$20
        EQUB    $80,$20,$80,$20,$80,$20,$80,$08
        EQUB    $10,$18,$20,$80,$20,$80,$20,$80
        EQUB    $20,$80,$20,$FF
.obj_sprite_data_B_generator
        EQUB    $01,$0F,$08,$06,$06,$EE,$01,$08
        EQUB    $01,$AA,$02,$AA,$04,$AA,$04,$AA
        EQUB    $08,$AB,$08,$AB,$08,$AB,$08,$AB
        EQUB    $04,$AA,$04,$AA,$02,$AA,$FF,$FF
        EQUB    $FF,$FF,$BB,$88,$11,$B8,$11,$B8
        EQUB    $11,$B8,$11,$FF

.obj_sprite_data_A_door_switch_right
        EQUB    $80,$80,$08,$88,$88,$88,$88,$88
        EQUB    $88,$88,$88,$88,$88,$80,$08,$80
        EQUB    $FF
.obj_sprite_data_B_door_switch_right
        EQUB    $0E,$01,$08,$04,$02,$02,$01,$01
        EQUB    $01,$01,$02,$02,$04,$01,$08,$0E

.obj_sprite_data_A_door_switch_left
        EQUB    $88,$80,$08,$80,$80,$80,$80,$80
        EQUB    $80,$80,$80,$80,$80,$80,$08,$88
        EQUB    $FF
.obj_sprite_data_B_door_switch_left
        EQUB    $07,$01,$08,$02,$04,$04,$08,$08
        EQUB    $08,$08,$04,$04,$02,$01,$08,$07

.obj_sprite_data_A_laser_turret_up_right
        EQUB    $88,$10,$18,$80,$08,$10,$18,$80
        EQUB    $10,$18,$80,$10,$18,$20,$80,$08
        EQUB    $18,$20,$90,$18,$20,$90,$18,$20
        EQUB    $98,$20,$98,$20,$A0,$A0,$A0,$A0
        EQUB    $A0,$FF
.obj_sprite_data_B_laser_turret_up_right
        EQUB    $60,$70,$80,$10,$90,$80,$60,$60
        EQUB    $60,$10,$80,$10,$80,$80,$F0,$F0
        EQUB    $60,$80,$E0,$10,$80,$10,$80,$60
        EQUB    $60,$10,$10,$10,$90,$90,$50,$50
        EQUB    $30,$72,$72,$30

.obj_sprite_data_A_laser_turret_down_right
        EQUB    $20,$A0,$A0,$A0,$A0,$98,$20,$98
        EQUB    $20,$90,$18,$20,$90,$18,$20,$80
        EQUB    $08,$18,$20,$80,$10,$18,$20,$80
        EQUB    $10,$18,$80,$08,$10,$18,$88,$10
        EQUB    $18,$FF
.obj_sprite_data_B_laser_turret_down_right
        EQUB    $30,$50,$50,$90,$90,$10,$10,$60
        EQUB    $10,$10,$80,$60,$E0,$10,$80,$F0
        EQUB    $F0,$60,$80,$80,$10,$80,$80,$60
        EQUB    $60,$10,$10,$90,$80,$60,$60,$70
        EQUB    $80

.obj_sprite_data_A_laser_turret_up_left
        EQUB    $88,$10,$18,$88,$10,$18,$20,$88
        EQUB    $10,$20,$80,$08,$10,$20,$80,$08
        EQUB    $18,$20,$80,$08,$10,$80,$08,$10
        EQUB    $80,$08,$80,$08,$80,$80,$80,$80
        EQUB    $80,$FF
.obj_sprite_data_B_laser_turret_up_left
        EQUB    $10,$E0,$60,$60,$10,$90,$80,$80
        EQUB    $60,$60,$10,$10,$80,$10,$10,$60
        EQUB    $F0,$F0,$10,$80,$70,$60,$10,$80
        EQUB    $80,$60,$80,$80,$90,$90,$A0,$A0
        EQUB    $C0

.obj_sprite_data_A_laser_turret_down_left
        EQUB    $00,$80,$80,$80,$80,$80,$08,$80
        EQUB    $08,$80,$08,$10,$80,$08,$10,$80
        EQUB    $08,$18,$20,$80,$08,$10,$20,$88
        EQUB    $10,$20,$88,$10,$18,$20,$88,$10
        EQUB    $18,$FF
.obj_sprite_data_B_laser_turret_down_left
        EQUB    $C0,$A0,$A0,$90,$90,$80,$80,$80
        EQUB    $60,$60,$10,$80,$10,$80,$70,$10
        EQUB    $60,$F0,$F0,$10,$10,$80,$10,$80
        EQUB    $60,$60,$60,$10,$90,$80,$10,$E0
        EQUB    $60

\ ******************************************************************************
\ * MANUAL ADDITIONS BELOW (not produced by sprite_editor.py).                  *
\ * If sprite_editor.py is re-run, these table entries and sprite blocks for    *
\ * gravity_well / bobbing_mine will be lost. Update OBJECT_NAMES in            *
\ * tools/sprite_codec.py (and provide source PNGs) before regenerating.        *
\ ******************************************************************************

\ Placeholder for OBJECT_gravity_well ($0D). The well never actually plots —
\ update_and_draw_all_objects early-exits before reaching the sprite path —
\ but the table needs an entry at this index so subsequent entries align.
.obj_sprite_data_A_gravity_well
        EQUB    $80,$FF
.obj_sprite_data_B_gravity_well
        EQUB    $00

\ Placeholder for OBJECT_bobbing_mine ($0E). Aliased to the fuel sprite for
\ now; replace via the sprite editor with a proper mine sprite.
obj_sprite_data_A_bobbing_mine = obj_sprite_data_A_fuel
obj_sprite_data_B_bobbing_mine = obj_sprite_data_B_fuel

.obj_sprite_data_A_table_LO
        EQUB    LO(obj_sprite_data_A_gun_up_right)
        EQUB    LO(obj_sprite_data_A_gun_down_right)
        EQUB    LO(obj_sprite_data_A_gun_up_left)
        EQUB    LO(obj_sprite_data_A_gun_down_left)
        EQUB    LO(obj_sprite_data_A_fuel)
        EQUB    LO(obj_sprite_data_A_pod_stand)
        EQUB    LO(obj_sprite_data_A_generator)
        EQUB    LO(obj_sprite_data_A_door_switch_right)
        EQUB    LO(obj_sprite_data_A_door_switch_left)
        EQUB    LO(obj_sprite_data_A_laser_turret_up_right)
        EQUB    LO(obj_sprite_data_A_laser_turret_down_right)
        EQUB    LO(obj_sprite_data_A_laser_turret_up_left)
        EQUB    LO(obj_sprite_data_A_laser_turret_down_left)
        EQUB    LO(obj_sprite_data_A_gravity_well)
        EQUB    LO(obj_sprite_data_A_bobbing_mine)

.obj_sprite_data_A_table_HI
        EQUB    HI(obj_sprite_data_A_gun_up_right)
        EQUB    HI(obj_sprite_data_A_gun_down_right)
        EQUB    HI(obj_sprite_data_A_gun_up_left)
        EQUB    HI(obj_sprite_data_A_gun_down_left)
        EQUB    HI(obj_sprite_data_A_fuel)
        EQUB    HI(obj_sprite_data_A_pod_stand)
        EQUB    HI(obj_sprite_data_A_generator)
        EQUB    HI(obj_sprite_data_A_door_switch_right)
        EQUB    HI(obj_sprite_data_A_door_switch_left)
        EQUB    HI(obj_sprite_data_A_laser_turret_up_right)
        EQUB    HI(obj_sprite_data_A_laser_turret_down_right)
        EQUB    HI(obj_sprite_data_A_laser_turret_up_left)
        EQUB    HI(obj_sprite_data_A_laser_turret_down_left)
        EQUB    HI(obj_sprite_data_A_gravity_well)
        EQUB    HI(obj_sprite_data_A_bobbing_mine)

.obj_sprite_data_B_table_LO
        EQUB    LO(obj_sprite_data_B_gun_up_right)
        EQUB    LO(obj_sprite_data_B_gun_down_right)
        EQUB    LO(obj_sprite_data_B_gun_up_left)
        EQUB    LO(obj_sprite_data_B_gun_down_left)
        EQUB    LO(obj_sprite_data_B_fuel)
        EQUB    LO(obj_sprite_data_B_pod_stand)
        EQUB    LO(obj_sprite_data_B_generator)
        EQUB    LO(obj_sprite_data_B_door_switch_right)
        EQUB    LO(obj_sprite_data_B_door_switch_left)
        EQUB    LO(obj_sprite_data_B_laser_turret_up_right)
        EQUB    LO(obj_sprite_data_B_laser_turret_down_right)
        EQUB    LO(obj_sprite_data_B_laser_turret_up_left)
        EQUB    LO(obj_sprite_data_B_laser_turret_down_left)
        EQUB    LO(obj_sprite_data_B_gravity_well)
        EQUB    LO(obj_sprite_data_B_bobbing_mine)

.obj_sprite_data_B_table_HI
        EQUB    HI(obj_sprite_data_B_gun_up_right)
        EQUB    HI(obj_sprite_data_B_gun_down_right)
        EQUB    HI(obj_sprite_data_B_gun_up_left)
        EQUB    HI(obj_sprite_data_B_gun_down_left)
        EQUB    HI(obj_sprite_data_B_fuel)
        EQUB    HI(obj_sprite_data_B_pod_stand)
        EQUB    HI(obj_sprite_data_B_generator)
        EQUB    HI(obj_sprite_data_B_door_switch_right)
        EQUB    HI(obj_sprite_data_B_door_switch_left)
        EQUB    HI(obj_sprite_data_B_laser_turret_up_right)
        EQUB    HI(obj_sprite_data_B_laser_turret_down_right)
        EQUB    HI(obj_sprite_data_B_laser_turret_up_left)
        EQUB    HI(obj_sprite_data_B_laser_turret_down_left)
        EQUB    HI(obj_sprite_data_B_gravity_well)
        EQUB    HI(obj_sprite_data_B_bobbing_mine)
